# Generated by Django 2.1 on 2019-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20190706_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ua',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', to='examapp.profiledata'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
