# Generated by Django 2.1 on 2019-07-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questios',
            new_name='questions',
        ),
    ]
