# Generated by Django 2.1 on 2019-07-06 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examapp', '0003_auto_20190706_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('username', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ua',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', to='examapp.profile'),
        ),
        migrations.DeleteModel(
            name='profiledata',
        ),
    ]
